var usmnt_players = [
/*//{'player': 'PLAYER',
	 'pos': 'POSISTION',
	 'ht': 'HEIGHT',
	 'wt': 'WEIGHT',
	 'birthdate': 'BIRTHDATE',
	 'hometoewn': 'HOMETOWN',
	 'club': 'CLUB/COLLEGE',
	 'img': 'portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 99,
	 'goals': 0,
	 'number': 99
	},
//*/
	{'player': 'Jozy Altidore',
	 'pos': 'Forward',
	 'ht': '6-1',
	 'wt': '175',
	 'birthdate': '11/6/89',
	 'hometown': 'Boca Raton, Fla.',
	 'club': 'Sunderland (England)',
	 'img': '2014-Altidore-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 70,
	 'goals': 23,
	 'number': 17
	},
	{'player': 'DaMarcus Beasley',
	 'pos': 'Defender',
	 'ht': '5-8',
	 'wt': '145',
	 'birthdate': '5/24/82',
	 'hometown': 'Ft. Wayne, Ind.',
	 'club': 'Puebla (Mexico)',
	 'img': '2014-Beasley-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 116,
	 'goals': 17,
	 'number': 7
	},
	{'player': 'Kyle Beckerman',
	 'pos': 'Midfielder',
	 'ht': '5-10',
	 'wt': '165',
	 'birthdate': '4/23/82',
	 'hometown': 'Crofton, Md.',
	 'club': 'Real Salt Lake',
	 'img': '2014-Beckerman-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 37,
	 'goals': 1,
	 'number': 15
	},
	{'player': 'Alejandro Bedoya',
	 'pos': 'Midfielder',
	 'ht': '5-10',
	 'wt': '160',
	 'birthdate': '4/29/87',
	 'hometown': 'Weston, Fla.',
	 'club': 'Nantes (France)',
	 'img': '2014-Bedoya-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 28,
	 'goals': 1,
	 'number': 11
	},
	{'player': 'Matt Besler',
	 'pos': 'Defender',
	 'ht': '6-0',
	 'wt': '170',
	 'birthdate': '2/11/87',
	 'hometown': 'Overland Park, Kan.',
	 'club': 'Sporting Kansas City',
	 'img': '2014-Besler-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 17,
	 'goals': 0,
	 'number': 5
	},
	{'player': 'Michael Bradley',
	 'pos': 'Midfielder',
	 'ht': '6-2',
	 'wt': '175',
	 'birthdate': '7/31/87',
	 'hometown': 'Manhattan Beach, Calif.',
	 'club': 'Toronto FC',
	 'img': '2014-Bradley-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 86,
	 'goals': 12,
	 'number': 4
	},
	{'player': 'John Brooks',
	 'pos': 'Defender',
	 'ht': '6-4',
	 'wt': '170',
	 'birthdate': '1/28/93',
	 'hometown': 'Berlin, Germany',
	 'club': 'Hertha Berlin (Germany)',
	 'img': '2014-Brooks-Portrait1.jpg',
	 'mug': 'mug.jpg',
	 'caps': 4,
	 'goals': 0,
	 'number': 6
	},
	{'player': 'Geoff Cameron',
	 'pos': 'Defender',
	 'ht': '6-3',
	 'wt': '185',
	 'birthdate': '7/11/85',
	 'hometown': 'Attleboro, Mass.',
	 'club': 'Stoke City (England)',
	 'img': '2014-Cameron-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 27,
	 'goals': 1,
	 'number': 20
	},
	{'player': 'Timothy Chandler',
	 'pos': 'Defender',
	 'ht': '6-1',
	 'wt': '180',
	 'birthdate': '3/29/90',
	 'hometown': 'Frankfurt, Germany',
	 'club': 'Eintracht Frankfurt (Germany)',
	 'img': '2014-Chandler-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 13,
	 'goals': 0,
	 'number': 21
	},
	{'player': 'Brad Davis',
	 'pos': 'Midfielder',
	 'ht': '5-11',
	 'wt': '165',
	 'birthdate': '11/8/81',
	 'hometown': 'St. Charles, Mo.',
	 'club': 'Houston Dynamo',
	 'img': '2014-Davis-Portrait-1.jpg',
	 'mug': 'mug.jpg',
	 'caps': 16,
	 'goals': 0,
	 'number': 14
	},
	{'player': 'Clint Dempsey',
	 'pos': 'Forward',
	 'ht': '6-1',
	 'wt': '170',
	 'birthdate': '3/9/83',
	 'hometown': 'Nacogdoches, Texas',
	 'club': 'Seattle Sounders FC',
	 'img': '2014-Dempsey-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 105,
	 'goals': 37,
	 'number': 8
	},
	{'player': 'Mix Diskerud',
	 'pos': 'Midfielder',
	 'ht': '6-0',
	 'wt': '150',
	 'birthdate': '10/2/90',
	 'hometown': 'Oslo, Norway',
	 'club': 'Rosenborg (Norway)',
	 'img': '2014-Diskerud-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 20,
	 'goals': 3,
	 'number': 10
	},
	{'player': 'Omar Gonzalez',
	 'pos': 'Defender',
	 'ht': '6-5',
	 'wt': '210',
	 'birthdate': '10/11/88',
	 'hometown': 'Dallas, Texas',
	 'club':  'LA Galaxy',
	 'img': '2014-Gonzalez-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 20,
	 'goals': 0,
	 'number': 3
	},
	{'player': 'Julian Green',
	 'pos': 'Midfielder',
	 'ht': '5-7',
	 'wt': '140',
	 'birthdate': '6/6/95',
	 'hometown': 'Tampa, Fla.',
	 'club': 'Bayern Munich (Germany)',
	 'img': '2014-Green-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 2,
	 'goals': 0,
	 'number': 16
	},
	{'player': 'Brad Guzan',
	 'pos': 'Goal Keeper',
	 'ht': '6-4',
	 'wt': '210',
	 'birthdate': '9/9/84',
	 'hometown': 'Homer Glen, Ill.',
	 'club': 'Aston Villa (England)',
	 'img': '2014-Guzan-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 25,
	 'goals': 0,
	 'number': 12
	},
	{'player': 'Tim Howard',
	 'pos': 'Goal Keeper',
	 'ht': '6-3',
	 'wt': '210',
	 'birthdate': '3/6/79',
	 'hometown': 'North Brunswick, N.J.',
	 'club': 'Everton (England)',
	 'img': '2014-Howard-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 100,
	 'goals': 0,
	 'number': 1
	},
	{'player': 'Aron Johannsson',
	 'pos': 'Forward',
	 'ht': '6-0',
	 'wt': '165',
	 'birthdate': '11/10/90',
	 'hometown': 'Mobile, Ala.',
	 'club': 'AZ Alkmaar (Netherlands)',
	 'img': '2014-Johannsson-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 8,
	 'goals': 2,
	 'number': 9
	},
	{'player': 'Fabian Johnson',
	 'pos': 'Defender',
	 'ht': '6-0',
	 'wt': '155',
	 'birthdate': '12/11/87',
	 'hometown': 'Munich, Germany',
	 'club': 'Borussia Moenchengladbach (Germany)',
	 'img': '2014-Johnson-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 22,
	 'goals': 1,
	 'number': 23
	},
	{'player': 'Jermaine Jones',
	 'pos': 'Midfielder',
	 'ht': '6-0',
	 'wt': '170',
	 'birthdate': '11/3/81',
	 'hometown': 'Chicago, Ill.',
	 'club': 'Besiktas (Turkey)',
	 'img': '2014-Jones-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 42,
	 'goals': 2,
	 'number': 13
	},
	{'player': 'Nick Rimando',
	 'pos': 'Goal Keeper',
	 'ht': '5-11',
	 'wt': '180',
	 'birthdate': '6/17/79',
	 'hometown': 'Montclair, Calif.',
	 'club': 'Real Salt Lake',
	 'img': '2014-Rimando-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 14,
	 'goals': 0,
	 'number': 22
	},
	{'player': 'Chris Wondolowski',
	 'pos': 'Forward',
	 'ht': '6-0',
	 'wt': '165',
	 'birthdate': '1/28/83',
	 'hometown': 'Danville, Calif.',
	 'club': 'San Jose Earthquakes',
	 'img': '2014-Wondolowski-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 21,
	 'goals': 9,
	 'number': 18
	},
	{'player': 'DeAndre Yedlin',
	 'pos': 'Defender',
	 'ht': '5-8',
	 'wt': '150',
	 'birthdate': '7/9/93',
	 'hometown': 'Seattle, Wash.',
	 'club': 'Seattle Sounders FC',
	 'img': '2014-Yedlin-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 4,
	 'goals': 0,
	 'number': 2
	},
	{'player': 'Graham Zusi',
	 'pos': 'Midfielder',
	 'ht': '5-10',
	 'wt': '160',
	 'birthdate': '8/18/86',
	 'hometown': 'Longwood, Fla.',
	 'club': 'Sporting Kansas City',
	 'img': '2014-Zusi-Portrait.jpg',
	 'mug': 'mug.jpg',
	 'caps': 23,
	 'goals': 3,
	 'number': 19
	},
];