/*

TODO: 
Add recent callups
Find/Add photos

JS will need to be updated to build quizes by filtering players to the desired set.

Maybe use a WP install to build the JSON? with all the custom fields.

Simplify with less fields? Really all we need is basic stats (caps/goals/position/birthday) and a photo

Deadline: Gold Cup


//http://en.wikipedia.org/wiki/United_States_men%27s_national_soccer_team
//http://soccerstats.us/teams/united-states/
http://www.ussoccerplayers.com/player/murray-bruce

http://en.wikipedia.org/wiki/United_States_national_soccer_team_results

//recent_callups = played for usmnt in the last 12 months
//http://en.wikipedia.org/wiki/United_States_men%27s_national_soccer_team#Recent_call-ups

*/
var usmnt_players = [
	{
		'player': 'Jeff Agoos',
		'first_name': 'Jeff',
		'last_name': 'Agoos',
		'pos': 'Defense',
		'birthdate':  'February 5, 1968',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/jeff-agoos-usmnt-biography.jpg',
		'caps': 134,
		'goals': 4,
		'first_callup':'January 13, 1988 – Guatemala – Friendly',
		'last_callup':'June 14, 2002 – Poland – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Juan Agudelo',
		'first_name': 'Juan',
		'last_name': 'Agudelo',
		'pos': 'Forward',
		'birthdate':  'November 23, 1992',
		'hometown': '',
		'club': 'New England Revolution',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/juan-agudelo-soccer-player.jpg',
		'caps': 20,
		'goals': 3,
		'first_callup':'November 17, 2010 – South Africa – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Jozy Altidore',
		'first_name': 'Jozy',
		'last_name': 'Altidore',
		'pos': 'Forward',
		'birthdate':  'November 6, 1989',
		'hometown': 'Boca Raton, FL',
		'club': 'Toronto FC',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Altidore-Portrait-1024x683.jpg',
		'caps': 80,
		'goals': 27,
		'first_callup':'November 17, 2007 – South Africa – Friendly',
		'last_callup':'March 31, 2015 – Switzerland – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'true',
	},
	{
		'player': 'Ventura Alvarado',
		'first_name': 'Ventura',
		'last_name': 'Alvarado',
		'pos': 'Defense',
		'birthdate':  'August 16, 1992',
		'hometown': 'Phoenix, Arizona',
		'club': 'Club América',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/04/VenturaAlvaradoClubAmerica1-Mexsport.jpg',
		'caps': 5,
		'goals': 0,
		'first_callup':'March 25, 2015 – Denmark – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Marcelo Balboa',
		'first_name': 'Marcelo',
		'last_name': 'Balboa',
		'pos': 'Defense',
		'birthdate':  'August 8, 1967',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/marcelo-balboa-1024x576.jpg',
		'caps': 128,
		'goals': 13,
		'first_callup':'January 10, 1988 – Guatemala – Friendly',
		'last_callup':'January 16, 2000 – Iran – Friendly',
		'hall_of_fame': 'true',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'DaMarcus Beasley',
		'first_name': 'DaMarcus',
		'last_name': 'Beasley',
		'pos': 'Defense',
		'birthdate':  'May 24, 1982',
		'hometown': '',
		'club': 'Houston Dynamo',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Beasley-Portrait-1024x683.jpg',
		'caps': 121,
		'goals': 17,
		'first_callup':'January 27, 2001 – China – Friendly',
		'last_callup':'July 01, 2014 – Belgium – World Cup',
		'hall_of_fame': 'true',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Kyle Beckerman',
		'first_name': 'Kyle',
		'last_name': 'Beckerman',
		'pos': 'Midfield',
		'birthdate':  'April 23, 1982',
		'hometown': '',
		'club': 'Real Salt Lake',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Beckerman-Portrait-1024x683.jpg',
		'caps': 45,
		'goals': 1,
		'first_callup':'January 20, 2007 – Denmark – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Alejandro Bedoya',
		'first_name': 'Alejandro',
		'last_name': 'Bedoya',
		'pos': 'Midfield',
		'birthdate':  'April 29, 1987',
		'hometown': '',
		'club': 'Nantes',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Bedoya-Portrait-1024x683.jpg',
		'caps': 39,
		'goals': 2,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'March 31, 2015 – Switzerland – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Tony Beltran',
		'first_name': 'Tony',
		'last_name': 'Beltran',
		'pos': '',
		'birthdate':  'October 11, 1987',
		'hometown': '',
		'club': 'Real Salt Lake',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/TonyBeltranUSMNT-ISIPHotos.com_.jpg',
		'caps': 3,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Matt Besler',
		'first_name': 'Matt',
		'last_name': 'Besler',
		'pos': 'Defense',
		'birthdate':  'February 11, 1987',
		'hometown': '',
		'club': 'Sporting Kansas City',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Besler-Portrait-1024x683.jpg',
		'caps': 25,
		'goals': 0,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Steve Birnbaum',
		'first_name': 'Steve',
		'last_name': 'Birnbaum',
		'pos': 'Defense',
		'birthdate':  'January 23, 1991',
		'hometown': '',
		'club': 'D.C. United',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/steve-birnbaum-usmnt.jpg',
		'caps': 1,
		'goals': 0,
		'first_callup':'November 14, 2014 – Colombia – Friendly',
		'last_callup':'January 28, 2015 – Chile – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Carlos Bocanegra',
		'first_name': 'Carlos',
		'last_name': 'Bocanegra',
		'pos': 'Defense',
		'birthdate':  'May 25, 1979',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/CarlosBocanegraStripes-ISIPhotos.com_1.jpg',
		'caps': 110,
		'goals': 14,
		'first_callup':'June 17, 2006 – Italy – World Cup',
		'last_callup':'June 26, 2010 – Ghana – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Terrence Boyd',
		'first_name': 'Terrence',
		'last_name': 'Boyd',
		'pos': 'Forward',
		'birthdate':  'February 16, 1991',
		'hometown': '',
		'club': 'RB Leipzig',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/TerrenceBoydStripes-ISIPHotos.com_1-1024x710-1024x710.jpg',
		'caps': 13,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Michael Bradley',
		'first_name': 'Michael',
		'last_name': 'Bradley',
		'pos': 'Midfield',
		'birthdate':  'July 31, 1987',
		'hometown': 'Manhattan Beach, CA',
		'club': 'Toronto FC',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Bradley-Portrait-1024x683.jpg',
		'caps': 98,
		'goals': 13,
		'first_callup':'June 12, 2010 – England – World Cup',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'true',
	},
	{
		'player': 'John Brooks',
		'first_name': 'John',
		'last_name': 'Brooks',
		'pos': 'Defense',
		'birthdate':  'January 28, 1993',
		'hometown': '',
		'club': 'Hertha Berlin',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Brooks-Portrait1-1024x683.jpg',
		'caps': 12,
		'goals': 2,
		'first_callup':'June 16, 2014 – Ghana – World Cup',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Paul Caligiuri',
		'first_name': 'Paul',
		'last_name': 'Caligiuri',
		'pos': 'Defense',
		'birthdate':  'March 9, 1964',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/paul-caligiuri-2.jpg',
		'caps': 110,
		'goals': 5,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'true',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Geoff Cameron',
		'first_name': 'Geoff',
		'last_name': 'Cameron',
		'pos': 'Defense',
		'birthdate':  'July 11, 1985',
		'hometown': '',
		'club': 'Stoke City',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Cameron-Portrait-1024x683.jpg',
		'caps': 31,
		'goals': 1,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'November 18, 2014 – Republic of Ireland – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Edgar Castillo',
		'first_name': 'Edgar',
		'last_name': 'Castillo',
		'pos': '',
		'birthdate':  'October 8, 1986',
		'hometown': '',
		'club': 'Atlas',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/EdgarCastilloUSMNT-ISIPhotos.com_3-1024x716-1024x716.jpg',
		'caps': 16,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Timothy Chandler',
		'first_name': 'Timothy',
		'last_name': 'Chandler',
		'pos': 'Defense',
		'birthdate':  'March 29, 1990',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Chandler-Portrait-1024x683.jpg',
		'caps': 21,
		'goals': 0,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Steve Cherundolo',
		'first_name': 'Steve',
		'last_name': 'Cherundolo',
		'pos': 'Defense',
		'birthdate':  'February 19, 1979',
		'hometown': 'Rockford, Illinois',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/SteveCherundolo-ISIPhotos.com_-1024x675.jpg',
		'caps': 87,
		'goals': 2,
		'first_callup':'June 12, 2006 – Czech Republic – World Cup',
		'last_callup':'June 26, 2010 – Ghana – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Joe Corona',
		'first_name': 'Joe',
		'last_name': 'Corona',
		'pos': '',
		'birthdate':  'July 9, 1990',
		'hometown': '',
		'club': 'Tijuana',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/joe_corona_130722_wg.jpg',
		'caps': 15,
		'goals': 2,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Brad Davis',
		'first_name': 'Brad',
		'last_name': 'Davis',
		'pos': 'Midfield',
		'birthdate':  'November 8, 1981',
		'hometown': '',
		'club': 'Houston Dynamo',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Davis-Portrait-1-1024x683.jpg',
		'caps': 17,
		'goals': 0,
		'first_callup':'June 26, 2014 – Germany – World Cup',
		'last_callup':'June 26, 2014 – Germany – World Cup',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Clint Dempsey',
		'first_name': 'Clint',
		'last_name': 'Dempsey',
		'pos': 'Forward',
		'birthdate':  'March 9, 1983',
		'hometown': 'Nacogdoches, TX',
		'club': 'Fulham',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Dempsey-Portrait-1024x683.jpg',
		'caps': 112,
		'goals': 40,
		'first_callup':'November 17, 2004 – Jamaica – World Cup Qualifier',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'true',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'true',
	},
	{
		'player': 'Mix Diskerud',
		'first_name': 'Mix',
		'last_name': 'Diskerud',
		'pos': 'Midfield',
		'birthdate':  'October 2, 1990',
		'hometown': '',
		'club': 'New York City',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Diskerud-Portrait-1024x683.jpg',
		'caps': 30,
		'goals': 6,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Landon Donovan',
		'first_name': 'Landon',
		'last_name': 'Donovan',
		'pos': 'Forward',
		'birthdate':  'March 4, 1982',
		'hometown': 'Ontario, CA',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Donovan-Portrait-1024x576.jpg',
		'caps': 157,
		'goals': 57,
		'first_callup':'June 05, 2002 – Portugal – World Cup',
		'last_callup':'October 10, 2014 – Ecuador – Friendly',
		'hall_of_fame': 'true',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Maurice Edu',
		'first_name': 'Maurice',
		'last_name': 'Edu',
		'pos': '',
		'birthdate':  'April 18, 1986',
		'hometown': '',
		'club': 'Philadelphia Union',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Maurice-Edu-USMNT-ISI-1024x765.jpg',
		'caps': 46,
		'goals': 1,
		'first_callup':'June 18, 2010 – Slovenia – World Cup',
		'last_callup':'June 26, 2010 – Ghana – World Cup',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Brad Evans',
		'first_name': 'Brad',
		'last_name': 'Evans',
		'pos': '',
		'birthdate':  'April 20, 1985',
		'hometown': '',
		'club': 'Seattle Sounders',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/brad-evans-belgium.jpg',
		'caps': 19,
		'goals': 1,
		'first_callup':'April 15, 2015 – Mexico – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Greg Garza',
		'first_name': 'Greg',
		'last_name': 'Garza',
		'pos': '',
		'birthdate':  'August 16, 1991',
		'hometown': '',
		'club': 'Tijuana',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Greg-Garza-USMNT-Colombia2014.jpg',
		'caps': 7,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Luis Gil',
		'first_name': 'Luis',
		'last_name': 'Gil',
		'pos': 'Midfield',
		'birthdate':  'January 14, 1993',
		'hometown': '',
		'club': 'Real Salt Lake',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/luis-gil.jpg',
		'caps': 2,
		'goals': 0,
		'first_callup':'February 8, 2015 – Panama – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Omar Gonzalez',
		'first_name': 'Omar',
		'last_name': 'Gonzalez',
		'pos': 'Defense',
		'birthdate':  'October 11, 1988',
		'hometown': '',
		'club': 'LA Galaxy',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Gonzalez-Portrait-1024x683.jpg',
		'caps': 25,
		'goals': 0,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Clarence Goodson',
		'first_name': 'Clarence',
		'last_name': 'Goodson',
		'pos': '',
		'birthdate':  'May 17, 1982',
		'hometown': '',
		'club': 'San Jose Earthquakes',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/clarence-goodson-1024x730.jpg',
		'caps': 46,
		'goals': 5,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Julian Green',
		'first_name': 'Julian',
		'last_name': 'Green',
		'pos': 'Midfield',
		'birthdate':  'June 6, 1995',
		'hometown': '',
		'club': 'Bayern Munich',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Green-Portrait-1024x683.jpg',
		'caps': 5,
		'goals': 1,
		'first_callup':'July 01, 2014 – Belgium – World Cup',
		'last_callup':'September 3, 2014 – Czech Republic – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Brad Guzan',
		'first_name': 'Brad',
		'last_name': 'Guzan',
		'pos': 'Goal Keeper',
		'birthdate':  'September 9, 1984',
		'hometown': '',
		'club': 'Aston Villa',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Guzan-Portrait-1024x683.jpg',
		'caps': 30,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Joe Gyau',
		'first_name': 'Joe',
		'last_name': 'Gyau',
		'pos': 'Forward',
		'birthdate':  'September 16, 1992',
		'hometown': '',
		'club': 'Borussia Dortmund II',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Joe-Gyau.jpg',
		'caps': 2,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'October 10, 2014 – Ecuador – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Bill Hamid',
		'first_name': 'Bill',
		'last_name': 'Hamid',
		'pos': '',
		'birthdate':  'November 25, 1990',
		'hometown': '',
		'club': 'D.C. United',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/bill-hamid.jpg',
		'caps': 2,
		'goals': 0,
		'first_callup':'November 18, 2014 – Republic of Ireland – Friendly',
		'last_callup':'November 18, 2014 – Republic of Ireland – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Matt Hedges',
		'first_name': 'Matt',
		'last_name': 'Hedges',
		'pos': 'Defense',
		'birthdate':  'April 1, 1990',
		'hometown': '',
		'club': 'FC Dallas',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Matt-Hedges-cover.jpg',
		'caps': 1,
		'goals': 0,
		'first_callup':'February 8, 2015 – Panama – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Tim Howard',
		'first_name': 'Tim',
		'last_name': 'Howard',
		'pos': 'Goal Keeper',
		'birthdate':  'March 6, 1979',
		'hometown': '',
		'club': 'Everton',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Howard-Portrait-1024x683.jpg',
		'caps': 104,
		'goals': 0,
		'first_callup':'June 12, 2010 – England – World Cup',
		'last_callup':'July 01, 2014 – Belgium – World Cup',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Emerson Hyndman',
		'first_name': 'Emerson',
		'last_name': 'Hyndman',
		'pos': '',
		'birthdate':  'April 9, 1996',
		'hometown': '',
		'club': 'Fulham',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/fulham-emerson-hyndman-us-soccer-player.jpg',
		'caps': 1,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'September 3, 2014 – Czech Republic – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Miguel Ibarra',
		'first_name': 'Miguel',
		'last_name': 'Ibarra',
		'pos': 'Midfield',
		'birthdate':  'March 15, 1993',
		'hometown': '',
		'club': 'Minnesota United',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/141014-MNT-v-HON-Miguel-Ibarra-1024x764.jpg',
		'caps': 3,
		'goals': 0,
		'first_callup':'October 14, 2014 – Honduras – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Aron Jóhannsson',
		'first_name': 'Aron',
		'last_name': 'Jóhannsson',
		'pos': 'Forward',
		'birthdate':  'November 10, 1990',
		'hometown': '',
		'club': 'AZ Alkmaar',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Johannsson-Portrait-1024x683.jpg',
		'caps': 12,
		'goals': 2,
		'first_callup':'June 16, 2014 – Ghana – World Cup',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Fabian Johnson',
		'first_name': 'Fabian',
		'last_name': 'Johnson',
		'pos': 'Defense',
		'birthdate':  'December 11, 1987',
		'hometown': '',
		'club': 'Borussia Moenchengladbach',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Johnson-Portrait-1024x683.jpg',
		'caps': 32,
		'goals': 1,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Eddie Johnson',
		'first_name': 'Eddie',
		'last_name': 'Johnson',
		'pos': 'Forward',
		'birthdate':  'March 31, 1984',
		'hometown': '',
		'club': 'D.C. United',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/eddie-johnson-1024x683.jpg',
		'caps': 63,
		'goals': 19,
		'first_callup':'June 12, 2006 – Czech Republic – World Cup',
		'last_callup':'June 22, 2006 – Ghana – World Cup',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Sean Johnson',
		'first_name': 'Sean',
		'last_name': 'Johnson',
		'pos': 'Goal Keeper',
		'birthdate':  'May 31, 1989',
		'hometown': '',
		'club': 'Chicago Fire',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Sean-Johnson-USMNT.jpg',
		'caps': 5,
		'goals': 0,
		'first_callup':'February 8, 2015 – Panama – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Jermaine Jones',
		'first_name': 'Jermaine',
		'last_name': 'Jones',
		'pos': 'Midfield',
		'birthdate':  'November 3, 1981',
		'hometown': '',
		'club': 'New England Revolution',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Jones-Portrait-1024x683.jpg',
		'caps': 50,
		'goals': 3,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Cobi Jones',
		'first_name': 'Cobi',
		'last_name': 'Jones',
		'pos': 'Midfield',
		'birthdate':  'June 16, 1970',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/cobi-jones-usmnt-biography.jpg',
		'caps': 164,
		'goals': 15,
		'first_callup':'June 05, 2002 – Portugal – World Cup',
		'last_callup':'June 21, 2002 – Germany – World Cup',
		'hall_of_fame': 'true',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Kasey Keller',
		'first_name': 'Kasey',
		'last_name': 'Keller',
		'pos': 'Goal Keeper',
		'birthdate':  'November 29, 1969',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/kasey-keller.jpg',
		'caps': 102,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Perry Kitchen',
		'first_name': 'Perry',
		'last_name': 'Kitchen',
		'pos': 'Defense',
		'birthdate':  'February 29, 1992',
		'hometown': '',
		'club': 'D.C. United',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/perrykitchen.jpg',
		'caps': 2,
		'goals': 0,
		'first_callup':'February 8, 2015 – Panama – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Sacha Kljestan',
		'first_name': 'Sacha',
		'last_name': 'Kljestan',
		'pos': '',
		'birthdate':  'September 9, 1985',
		'hometown': '',
		'club': 'New York Red Bulls',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Sacha-Kljestan.jpg',
		'caps': 46,
		'goals': 4,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Alexi Lalas',
		'first_name': 'Alexi',
		'last_name': 'Lalas',
		'pos': 'Defense',
		'birthdate':  'June 1, 1970',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/alexi-lalas1-1024x746.jpg',
		'caps': 96,
		'goals': 9,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Brian McBride',
		'first_name': 'Brian',
		'last_name': 'McBride',
		'pos': 'Forward',
		'birthdate':  'June 19, 1972',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/brian-mcbride.jpg',
		'caps': 95,
		'goals': 30,
		'first_callup':'June 05, 2002 – Portugal – World Cup',
		'last_callup':'June 22, 2006 – Ghana – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Tony Meola',
		'first_name': 'Tony',
		'last_name': 'Meola',
		'pos': 'Goal Keeper',
		'birthdate':  'February 21, 1969',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/tony-meola.jpg',
		'caps': 100,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Joe-Max Moore',
		'first_name': 'Joe-Max',
		'last_name': 'Moore',
		'pos': 'Forward',
		'birthdate':  'February 23, 1971',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/joe-max-moore-usmnt-biograp.jpg',
		'caps': 100,
		'goals': 24,
		'first_callup':'June 05, 2002 – Portugal – World Cup',
		'last_callup':'June 14, 2002 – Poland – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Alfredo Morales',
		'first_name': 'Alfredo',
		'last_name': 'Morales',
		'pos': '',
		'birthdate':  'May 12, 1990',
		'hometown': '',
		'club': 'Ingolstadt 04',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Alfredo-Morales-USMNT-Getty-Images.jpg',
		'caps': 10,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Jordan Morris',
		'first_name': 'Jordan',
		'last_name': 'Morris',
		'pos': 'Forward',
		'birthdate':  'October 26, 1994',
		'hometown': '',
		'club': 'Stanford University',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Jordan-Morris.jpeg',
		'caps': 5,
		'goals': 1,
		'first_callup':'November 18, 2014 – Republic of Ireland – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Bruce Murray',
		'first_name': 'Bruce',
		'last_name': 'Murray',
		'pos': 'Midfield',
		'birthdate':  'January 25, 1966',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/bruce-murray.jpg',
		'caps': 85,
		'goals': 21,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'true',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Lee Nguyen',
		'first_name': 'Lee',
		'last_name': 'Nguyen',
		'pos': 'Midfield',
		'birthdate':  'December 7, 1985',
		'hometown': '',
		'club': 'New England Revolution',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/lee-nguyen-colombia-friendly-november-2014.jpg',
		'caps': 6,
		'goals': 0,
		'first_callup':'November 14, 2014 – Colombia – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Oguchi Onyewu',
		'first_name': 'Oguchi',
		'last_name': 'Onyewu',
		'pos': '',
		'birthdate':  'May 13, 1982',
		'hometown': '',
		'club': 'England Charlton Athletic',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/oguchi-onyewu.jpg',
		'caps': 69,
		'goals': 6,
		'first_callup':'June 12, 2006 – Czech Republic – World Cup',
		'last_callup':'June 18, 2010 – Slovenia – World Cup',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Michael Orozco',
		'first_name': 'Michael',
		'last_name': 'Orozco',
		'pos': '',
		'birthdate':  'February 7, 1986',
		'hometown': '',
		'club': 'Puebla',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Michael-Orozco.jpg',
		'caps': 16,
		'goals': 3,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'June 05, 2015 – Netherlands – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Michael Parkhurst',
		'first_name': 'Michael',
		'last_name': 'Parkhurst',
		'pos': '',
		'birthdate':  'January 24, 1984',
		'hometown': '',
		'club': 'Columbus Crew',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Michael-Parkhurst-USMNT-Guatemala2012.jpg',
		'caps': 25,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Tim Ream',
		'first_name': 'Tim',
		'last_name': 'Ream',
		'pos': '',
		'birthdate':  'October 5, 1987',
		'hometown': '',
		'club': 'Bolton Wanderers',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/tim-ream.jpg',
		'caps': 13,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'March 31, 2015 – Switzerland – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Claudio Reyna',
		'first_name': 'Claudio',
		'last_name': 'Reyna',
		'pos': 'Midfield',
		'birthdate':  'July 20, 1973',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/claudio-reyna.jpg',
		'caps': 111,
		'goals': 8,
		'first_callup':'June 10, 2002 – South Korea – World Cup',
		'last_callup':'June 22, 2006 – Ghana – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Nick Rimando',
		'first_name': 'Nick',
		'last_name': 'Rimando',
		'pos': 'Goal Keeper',
		'birthdate':  'June 17, 1979',
		'hometown': '',
		'club': 'Real Salt Lake',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Rimando-Portrait-1024x683.jpg',
		'caps': 21,
		'goals': 0,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Rubio Rubin',
		'first_name': 'Rubio',
		'last_name': 'Rubin',
		'pos': 'Forward',
		'birthdate':  'March 1, 1996',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Rubio-Rubin-1024x768.jpg',
		'caps': 3,
		'goals': 0,
		'first_callup':'November 18, 2014 – Republic of Ireland – Friendly',
		'last_callup':'March 25, 2015 – Denmark – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Brek Shea',
		'first_name': 'Brek',
		'last_name': 'Shea',
		'pos': 'Midfield',
		'birthdate':  'February 28, 1990',
		'hometown': '',
		'club': 'Orlando City',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/SheaWhite_crop_north.jpg',
		'caps': 33,
		'goals': 4,
		'first_callup':'September 3, 2014 – Czech Republic – Friendly',
		'last_callup':'June 05, 2015 – Netherlands – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Jonathan Spector',
		'first_name': 'Jonathan',
		'last_name': 'Spector',
		'pos': '',
		'birthdate':  'March 1, 1986',
		'hometown': '',
		'club': 'Birmingham City',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/jonathan-spector-birmingham-city.jpg',
		'caps': 34,
		'goals': 0,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Earnie Stewart',
		'first_name': 'Earnie',
		'last_name': 'Stewart',
		'pos': 'Midfield',
		'birthdate':  'March 28, 1969',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/earnie-stewart.jpg',
		'caps': 101,
		'goals': 17,
		'first_callup':'June 05, 2002 – Portugal – World Cup',
		'last_callup':'June 21, 2002 – Germany – World Cup',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Wil Trapp',
		'first_name': 'Wil',
		'last_name': 'Trapp',
		'pos': 'Midfield',
		'birthdate':  'January 15, 1993',
		'hometown': '',
		'club': 'Columbus Crew',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/wil-trapp.jpg',
		'caps': 1,
		'goals': 0,
		'first_callup':'November 14, 2014 – Colombia – Friendly',
		'last_callup':'January 28, 2015 – Chile – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Daniel Williams',
		'first_name': 'Daniel',
		'last_name': 'Williams',
		'pos': '',
		'birthdate':  'March 8, 1989',
		'hometown': '',
		'club': 'Reading',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/DannyWilliamsHonduras1-ISIPhotos-1024x829.jpg',
		'caps': 16,
		'goals': 1,
		'first_callup':'March 31, 2015 – Switzerland – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'true',
		'current_squad': 'false',
	},
	{
		'player': 'Chris Wondolowski',
		'first_name': 'Chris',
		'last_name': 'Wondolowski',
		'pos': 'Forward',
		'birthdate':  'January 28, 1983',
		'hometown': '',
		'club': 'San Jose Earthquakes',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Wondolowski-Portrait-1024x683.jpg',
		'caps': 27,
		'goals': 9,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'February 8, 2015 – Panama – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Bobby Wood',
		'first_name': 'Bobby',
		'last_name': 'Wood',
		'pos': 'Forward',
		'birthdate':  'January 15, 1992',
		'hometown': '',
		'club': 'Erzgebirge Aue',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/bobby-wood.jpg',
		'caps': 7,
		'goals': 2,
		'first_callup':'October 10, 2014 – Ecuador – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Eric Wynalda',
		'first_name': 'Eric',
		'last_name': 'Wynalda',
		'pos': 'Forward',
		'birthdate':  'June 9, 1969',
		'hometown': '',
		'club': '',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/eric-wynalda.jpg',
		'caps': 106,
		'goals': 34,
		'first_callup':'',
		'last_callup':'',
		'hall_of_fame': 'false',
		'retired': 'true',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'William Yarbrough',
		'first_name': 'William',
		'last_name': 'Yarbrough',
		'pos': 'Goal Keeper',
		'birthdate':  'March 20, 1989',
		'hometown': 'Aguascalientes, Mexico',
		'club': 'León',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/04/atlas-leon-10.jpg',
		'caps': 2,
		'goals': 0,
		'first_callup':'March 31, 2015 – Switzerland – Friendly',
		'last_callup':'April 15, 2015 – Mexico – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'DeAndre Yedlin',
		'first_name': 'DeAndre',
		'last_name': 'Yedlin',
		'pos': 'Defense',
		'birthdate':  'July 9, 1993',
		'hometown': '',
		'club': 'Tottenham Hotspur',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Yedlin-Portrait-1024x683.jpg',
		'caps': 17,
		'goals': 0,
		'first_callup':'June 22, 2014 – Portugal – World Cup',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
	{
		'player': 'Gyasi Zardes',
		'first_name': 'Gyasi',
		'last_name': 'Zardes',
		'pos': 'Forward',
		'birthdate':  'September 2, 1991',
		'hometown': '',
		'club': 'LA Galaxy',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/Gyasi-Zardes-2.jpg',
		'caps': 7,
		'goals': 1,
		'first_callup':'November 14, 2014 – Colombia – Friendly',
		'last_callup':'June 10, 2015 – Germany – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'true',
		'current_squad': 'false',
	},
	{
		'player': 'Graham Zusi',
		'first_name': 'Graham',
		'last_name': 'Zusi',
		'pos': 'Midfield',
		'birthdate':  'August 18, 1986',
		'hometown': '',
		'club': 'Sporting Kansas City',
		'img': 'https://app.circlecube.com/usmnt/wp-content/uploads/sites/2/2015/03/2014-Zusi-Portrait-1024x683.jpg',
		'caps': 28,
		'goals': 3,
		'first_callup':'June 07, 2014 – Nigeria – Friendly',
		'last_callup':'October 14, 2014 – Honduras – Friendly',
		'hall_of_fame': 'false',
		'retired': 'false',
		'recent_callups': 'false',
		'current_squad': 'false',
	},
];

var usmnt_coaches = [
	{
	'player': 'Jurgen Klinsmann',
	'pos': 'Coach',
	'ht': '5\'11"',
	'wt': '161',
	'birthdate': '07/30/1964',
	'hometown': 'Göppingen, Germany',
	'club': 'Germany National Team',
	'img': 'JurgenKlinsmannUSMNT1-HondurasHomeWCQ2013-ISIPhotos.jpg',
	'img_pos': 'center center',
	'img2': '051414-USMNT-30-man-Preliminary-Roster-USA-manager-Juergen-Klinsmann.jpg',
	'img2_pos': 'center center',
	'caps': 108,
	'goals': 47,
	'number': null,
	},
	//Bob Bradley
	//Bruce Arena
];
/*
http://en.wikipedia.org/wiki/United_States_men%27s_national_soccer_team
Special Thanks
 http://www.ussoccer.com/mens-national-team/latest-roster
 http://www.wjla.com/articles/2014/06/us-world-cup-team-player-capsules-103892.html
Images:
 http://ussoccer.com
 http://msn.foxsports.com/soccer/photos/meet-team-united-states-world-cup-roster-23-man-squad-brazil-051314
*/